### ISSUE TITLE
Multi language system

### ISSUE THREAD

**Issue by lazypwny751** [jpsspm/sspm#3]
Dear maintainer, can make multi language system with associative arrays and using source, also you can check the requirements in init.

**Comment by jpsspm** [comment]
Hi Sir! I do not really understand your request
Is there an issue in the code ?
What do you mean by 'multi language system' ?

Thanks.

**Comment by lazypwny751** [comment]
Je suis desole pour j'ai pas vu votre message, je dire que vous faire multiple dossier pour autre languages comme [sspm/fr](https://github.com/jpsspm/sspm/tree/main/fr) ou [sspm/en](https://github.com/jpsspm/sspm/tree/main/en), mais vous n'avez pas besoin de faire ça, vous pouvez utulise associative arrays pour languages:
```bash
#!/bin/bash

#export LANG="tr_TR"
#export LANG="fr_FR"

# automatique   
case "${LANG%.*}"  in
    tr_TR)
        export lang=(
            [hello]="merhaba"
)
    ;;
    fr_FR)
        export lang=(
            [hello]="bonjourne"
)
    ;;
    *)
        export lang=(
            [hello]="hello"
)
    ;;
esac

echo "${lang[hello]}"
```
si vous voulez je peux vous aider.

**Comment by jpsspm** [comment]
I again, I see the idea.

I separated the French version of the script because dealing with French characteres is really complex
the French version has UTF-8 (hex.) display format, so we have hex codes in almost all 'printf' commands 

there are several 'grep/sed' commands in the script
for example in a full French configured locale
the output of the 'file' command can be different from an English locale

because we sometimes grep/write/sed in the script, in some cases we need static/unvariable text in the script.
reason why I didn't use auto-translation tools (the idea is to create less dependencies to the system)

the french version doesn't really depend on which 'LANG=' you are using
in this way, this will help French users to still have french outputs even if the "LANG" is not properly formatted


------------------------------------------------------------------------------------------------------------------------------------------------------------

If that will keep the sspm concept:

of being **one single and main script** which does everything [**All In One**]
&emsp;&emsp;&emsp;(not something like source ../pkgremove or source dir/another_script)
</br></br>
Lets do that! :)

**Comment by lazypwny751** [comment]
aha okay understood so the concept like "kiss package manager", of course we can keep the concept, can be functionalize like:
```bash

sspm:lang:en() {
    if [[ "${LANG##*.}" != "UTF-8" ]] ; then
        export LANG="${LANG%.*}.UTF-8"
   fi
    case "${1}" in
        hello)
            printf "hello\n"
        ;;
    esac
}

sspm:lang:fr() {
    if [[ "${LANG##*.}" != "UTF-16" ]] ; then
        export LANG="${LANG%.*}.UTF-16"
   fi
    case "${1}" in
        hello)
            printf "bonjourné\n"
        ;;
    esac
}
```

we can check the unicode translation encoding with this method, also the first method can still be used, non-static variables can also be used in arrays. It is possible to do all this in the main file for all languages.

```bash
case "${LANG%.*}"  in
    tr_TR)
        export lang=(
            [hello]="merhaba $(whoami)"
)
    ;;
    fr_FR)
        export lang=(
            [hello]="bonjourne $(whoami)"
)
    ;;
    *)
        export lang=(
            [hello]="hello $(whoami)"
)
    ;;
esac
```

**Comment by jpsspm** [comment]
-----------------------------------------------------------------------------------------------------------
I didn't known about the "kiss package manager" but yes exactly
-----------------------------------------------------------------------------------------------------------
Dealing with this will need to make many adjustments almost everywhere
-----------------------------------------------------------------------------------------------------------
I will create a new folder and put a copy of sspm in which will be a development  version of sspm
with **Multi language system** support, and if everything goes fine, this will be the replacement of main scripts
........................................................................................................................... 

I also see that you want to add a support for your language
As a test translate the **manual page**  and the the 1st sspm printf command (dialog)
and show me concretely how you will set up a output in 3 different languages.

**Comment by lazypwny751** [comment]
sure, i got a fork for testing and can push the code to test (or any sub-branch). Yes, 😄 I added my language as an example, my purpose here was to show that compatibility with other languages ​​will be offered easily thanks to this system.
